version: "3.1"

services:
  futhwe:
    image: registry.zepto.vn/web3/futhwe:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_PORT=50051
    ports:
      - "50051:50051"
    volumes:
      - ./env.yml:/app/env.yml
